import sys
sys.path.append('C:/Users/Fei/OngoingProjects/Force_based_fiber_beam_element/small_disp_fiberbeam/test_code_1/fiber_beam_model')
# import necessary modules
import numpy as np
from fiber_beam_model import *
material = KentParkModel(1, 41.37, 1.048, -0.0096, 128.205)
fiber = Fiber([0., 0.5], 1/10000, material)
print('strain=', fiber.get_fiber_strain())
print('stress=', fiber.get_fiber_stress())
print('Et=', fiber.get_fiber_tangent_stiffness())
print('peeq=', fiber.get_fiber_PEEQ())
fiber.update_change_in_fiber_strain_incr(np.array([-0.0134384, -0.0403152, -0.050644 ]))
fiber.update_material_parameters_in_loadstep()
fiber.update_fiber_strain_incr()
fiber.update_fiber_strain()
fiber.update_fiber_stress()
fiber.update_fiber_tangent_stiffness()
fiber.update_fiber_PEEQ()
print('get_change_in_fiber_strain_incr = ', fiber.get_change_in_fiber_strain_incr())
print('strain=', fiber.get_fiber_strain())
print('stress=', fiber.get_fiber_stress())
print('Et=', fiber.get_fiber_tangent_stiffness())
print('peeq=', fiber.get_fiber_PEEQ())
'''
fiber.update_change_in_fiber_strain_incr(np.array([0.,-0.002,0.]))
fiber.update_material_parameters_in_loadstep()
fiber.update_fiber_strain_incr()
fiber.update_fiber_strain()
fiber.update_fiber_stress()
fiber.update_fiber_tangent_stiffness()
fiber.update_fiber_PEEQ()
print('strain=', fiber.get_fiber_strain())
print('stress=', fiber.get_fiber_stress())
print('Et=', fiber.get_fiber_tangent_stiffness())
print('peeq=', fiber.get_fiber_PEEQ())
fiber.update_change_in_fiber_strain_incr(np.array([0.,-0.002,0.]))
fiber.update_material_parameters_in_loadstep()
fiber.update_fiber_strain_incr()
fiber.update_fiber_strain()
fiber.update_fiber_stress()
fiber.update_fiber_tangent_stiffness()
fiber.update_fiber_PEEQ()
print('strain=', fiber.get_fiber_strain())
print('stress=', fiber.get_fiber_stress())
print('Et=', fiber.get_fiber_tangent_stiffness())
print('peeq=', fiber.get_fiber_PEEQ())
fiber.update_change_in_fiber_strain_incr(np.array([0.,-0.002,0.]))
fiber.update_material_parameters_in_loadstep()
fiber.update_fiber_strain_incr()
fiber.update_fiber_strain()
fiber.update_fiber_stress()
fiber.update_fiber_tangent_stiffness()
fiber.update_fiber_PEEQ()
print('strain=', fiber.get_fiber_strain())
print('stress=', fiber.get_fiber_stress())
print('Et=', fiber.get_fiber_tangent_stiffness())
print('peeq=', fiber.get_fiber_PEEQ())
'''
