import sys
sys.path.append('C:/Users/Fei/OngoingProjects/Force_based_fiber_beam_element/small_disp_fiberbeam/test_code_1/fiber_beam_model')
# import necessary modules
import numpy as np
from fiber_beam_model import *
material_array = np.array([[MenegottoPintoModel(1, 20000, 580, 60, 20, 18.5, 0.0002), MenegottoPintoModel(1, 20000, 580, 60, 20, 18.5, 0.0002)], [MenegottoPintoModel(1, 20000, 580, 60, 20, 18.5, 0.0002), MenegottoPintoModel(1, 20000, 580, 60, 20, 18.5, 0.0002)]], dtype=Fiber)
fiber_array = np.array([[Fiber([-1., -1.], 1., material_array[0,0]), Fiber([-1., 1.], 1., material_array[0,1])], [Fiber([1., -1.], 1., material_array[1,0]), Fiber([1., 1.], 1., material_array[1,1])]], dtype=Fiber)
sec = Section(0., [4., 4.], fiber_array, 1e-5)
sec.update_sec_stiffness_matrix()
sec.update_change_in_secforce_incr(100*np.array([0., 0., -1., 1., 0.]))
sec.update_change_in_secdisp_incr()
sec.update_secforce_incr()
sec.update_secforces()
sec.update_secdisp_incr()
sec.update_fiber_parameters_in_loadstep()
sec.update_sec_stiffness_matrix()
sec.update_secforces()
sec.update_residual_secdisps()
sec.update_change_in_secforce_incr(-100*np.array([0., 0., -1., 1., 0.]))
sec.update_change_in_secdisp_incr()
sec.update_secforce_incr()
sec.update_secforces()
sec.update_secdisp_incr()
sec.update_fiber_parameters_in_loadstep()
sec.update_sec_stiffness_matrix()
sec.update_secforces()
sec.update_residual_secdisps()
print(sec.get_secforces())
print(sec.get_sec_stiffness_matrix())
